### ISSUE TITLE
To work in Catalina (macOS 10.15.7) NSToolbarSidebarTrackingSeparatorItemIdentifier had to be removed

### ISSUE THREAD

**Issue by GrxE** [ryanmcgrath/cacao#11]
Hi, 
first of all, GREAT WORK! I had no problems getting some examples to run in 10.15.7 - but unfortunately the NSToolbarSidebarTrackingSeparatorItemIdentifier is part of macOS 11 and I got a compile error on my Catalina (10.15.7) system:

  ```
 note: Undefined symbols for architecture x86_64:
            "_NSToolbarSidebarTrackingSeparatorItemIdentifier", referenced from:
                cacao::macos::toolbar::enums::ItemIdentifier::to_nsstring::h93aee7ff60b47338 in libcacao-666ce155f0266e01.rlib(cacao-666ce155f0266e01.cacao.6ipigaqo-cgu.15.rcgu.o)
          ld: symbol(s) not found for architecture x86_64
```

I removed the Enum-entry and corresponding code and got the todo_list compiled and running. No Crashes or bugs (so far). Here is my modified enums.rs 
[enums.txt](https://github.com/ryanmcgrath/cacao/files/6721502/enums.txt)

**Comment by ryanmcgrath** [comment]
Ah, yeah, I think I probably blanket replaced that - it should really just be hard coded to the enum value so it can compile on 10.15.7-, or there needs to be some kind of compile time check.

Will see what I can throw together… appreciate it!

**Comment by ryanmcgrath** [comment]
@GrxE curious if the patch I just threw up works for you. If so, I can push a `0.2.1` to crates.io.

Thanks again!

**Comment by ryanmcgrath** [comment]
`0.2.1` should fix this.
